# Generated by Django 2.2.3 on 2019-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('aptitudeId', models.AutoField(primary_key=True, serialize=False)),
                ('aptitudeName', models.CharField(help_text='Conducted By', max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gd',
            fields=[
                ('gdId', models.AutoField(primary_key=True, serialize=False)),
                ('gdName', models.CharField(help_text='Group Discussion Topic', max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internshipId', models.AutoField(primary_key=True, serialize=False)),
                ('internshipName', models.CharField(help_text='Internship Name', max_length=100)),
                ('internshipDetails', models.CharField(help_text='Description', max_length=225)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('mockinterviewid', models.AutoField(primary_key=True, serialize=False)),
                ('mockinterviewName', models.CharField(help_text='Conducted By', max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resumeId', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
