# Generated by Django 2.2.1 on 2019-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('yearId', models.AutoField(primary_key=True, serialize=False)),
                ('yearName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(choices=[('TCS', 'TCS'), ('Infosycs', 'Infosycs'), ('Wipro', 'Wipro'), ('Percistence', 'Percistence'), ('Godrej', 'Godrej'), ('Compscop', 'Compscop')], help_text='Company Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterid', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
