# Generated by Django 2.2.1 on 2019-07-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('branchId', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(choices=[('computer', 'computer'), ('Mech', 'Mech'), ('civil', 'civil'), ('ETC', 'Etc')], help_text='Branch Name', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(choices=[('TCS', 'TCS'), ('Infosycs', 'Infosycs'), ('Wipro', 'Wipro'), ('Percistence', 'Percistence'), ('Godrej', 'Godrej'), ('IFB', 'IFB'), ('LNT', 'LNT'), ('Siemens', 'Siemens')], help_text='Company Name', max_length=100),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('percent', models.IntegerField(help_text='Percentage', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=10, null=True)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentBranchId', to='placement_app.Branche')),
                ('semesterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentSemesterId', to='placement_app.Semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AcademicYearId', to='placement_app.AcademicYear')),
            ],
            options={
                'ordering': ['-user'],
                'permissions': (('is_student', 'is_student'),),
            },
        ),
    ]
