# Generated by Django 2.2.3 on 2019-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designationId', models.AutoField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(choices=[('Trainee Engineer', 'Trainee Engineer'), ('Software Engineer', 'Software Engineer'), ('System Analyst', 'System Analyst'), ('Programmer Analyst', 'Programmer Analyst'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Project Lead', 'Project Lead'), ('Project Manager', 'Project Manager'), ('Program Manager', 'Program Manager'), ('Architect', 'Architect'), ('Technical Specialist', 'Technical Specialist'), ('Deliver Manager', 'Deliver Manager'), ('Delivery Head', 'Delivery Head'), ('Business Analyst', 'Business Analyst'), ('Director Technology', 'Director Technology'), ('Director', 'Director'), ('Vice President', 'Vice president'), ('President', 'President'), ('CEO', 'CEO')], help_text='Designation Name', max_length=100)),
            ],
        ),
    ]
