# Generated by Django 2.2.1 on 2019-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('infoId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(help_text='Internship Name', max_length=100)),
                ('designationDetails', models.CharField(help_text='Description', max_length=225)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
